#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pbr
Version  : 5.9.0
Release  : 123
URL      : https://files.pythonhosted.org/packages/96/9f/f4bc832eeb4ae723b86372277da56a5643b0ad472a95314e8f516a571bb0/pbr-5.9.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/96/9f/f4bc832eeb4ae723b86372277da56a5643b0ad472a95314e8f516a571bb0/pbr-5.9.0.tar.gz
Summary  : Python Build Reasonableness
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: pypi-pbr-bin = %{version}-%{release}
Requires: pypi-pbr-license = %{version}-%{release}
Requires: pypi-pbr-python = %{version}-%{release}
Requires: pypi-pbr-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi-pytest

%description
Introduction
============
.. image:: https://img.shields.io/pypi/v/pbr.svg
:target: https://pypi.python.org/pypi/pbr/
:alt: Latest Version

%package bin
Summary: bin components for the pypi-pbr package.
Group: Binaries
Requires: pypi-pbr-license = %{version}-%{release}

%description bin
bin components for the pypi-pbr package.


%package license
Summary: license components for the pypi-pbr package.
Group: Default

%description license
license components for the pypi-pbr package.


%package python
Summary: python components for the pypi-pbr package.
Group: Default
Requires: pypi-pbr-python3 = %{version}-%{release}

%description python
python components for the pypi-pbr package.


%package python3
Summary: python3 components for the pypi-pbr package.
Group: Default
Requires: python3-core
Provides: pypi(pbr)

%description python3
python3 components for the pypi-pbr package.


%prep
%setup -q -n pbr-5.9.0
cd %{_builddir}/pbr-5.9.0
pushd ..
cp -a pbr-5.9.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656389216
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pytest || :
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pbr
cp %{_builddir}/pbr-5.9.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pbr/294b43b2cec9919063be1a3b49e8722648424779
cp %{_builddir}/pbr-5.9.0/pbr/tests/testpackage/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pbr/18184784896860da31dc6210e80eafa871d7a253
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pbr

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pbr/18184784896860da31dc6210e80eafa871d7a253
/usr/share/package-licenses/pypi-pbr/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
